# Generated by Django 3.2 on 2023-03-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='Invoice_date',
            field=models.DateTimeField(),
        ),
    ]
