# Generated by Django 3.2 on 2023-03-26 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_invoice_invoice_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='Invoice_date',
            new_name='invoice_date',
        ),
    ]
